5 tasks from 2 module
js-tasks-ru/jsbasic-20230302_zubokryl pull request #2
Opened 2023-03-10 21:35 UTC by Zubokryl

Could you please explain why the 5th task has failed npm test? I couldn't understand the error...

2023-03-10 21:36 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-11 14:07 UTC, SinimaWath requested changes

2023-03-11 14:07 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  if (str.length <= maxlength) {
Error: Expected 'Вот, что м...' to be 'Вот, что …'.

`Вот, что м...` - то что возвращает твоя функция
`Вот, что …` - то что ожидает тест

2023-03-12 06:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-03-13 13:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-03-13 15:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2023-03-14 21:16 UTC, SinimaWath approved these changes

2023-03-14 21:17 UTC, merged